version: '3.8'

services:
  loadbalancer:
    build: 
      context: ..
      dockerfile: deployments/Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - ../config:/app/config
    environment:
      - CONFIG_FILE=/app/config/config.yaml