server:
  listen_addr: "127.0.0.1:8080"
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 120s

load_balancer:
  algorithm: "round-robin"
  health_check_interval: 10s

backend_servers:
  - "http://localhost:8081"
  - "http://localhost:8082"
  - "http://localhost:8083"

tls:
  enabled: false
  cert_file: ""
  key_file: ""

logging:
  level: "info"
  format: "json"

metrics:
  enabled: true
  port: 9090

feature_toggles:
  enable_circuit_breaker: true
  enable_rate_limiting: false
