server:
  port: 8080
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 120s

load_balancer:
  algorithm: round-robin
  health_check_interval: 10s

backend_servers:
  - http://localhost:8081
  - http://localhost:8082
  - http://localhost:8083

logging:
  level: info
  format: json

metrics:
  enabled: true
  port: 9090
